name: 'Build Target Pre Processor'
description: 'To create build target matrix from selected target plaforms list'
inputs:
  buildEnvironment:
    required: false
    description: 'Build Environment'
    default: 'Development'
  buildTargetOne: 
    required: false
    description: 'Build target one'
    default: 'Android'
  buildTargetTwo: 
    required: false
    description: 'Build target two'
    default: 'None'
  buildTargetThree: 
    required: false
    description: 'Build target three'
    default: 'None'
  buildTargetFour: 
    required: false
    description: 'Build target four'
    default: 'None'
  os: 
    required: false
    description: 'Operating system for builds'
    default: '{"Windows":"self-hosted-windows-test","Mac":"self-hosted-mac-test","Common":"self-hosted-build-runner"}'
outputs:
  selectedTarget:
    description: Generated matrix
runs:
  using: 'node12'
  main: 'dist/index.js'
