name: 'Build Target Pre Processor'
description: 'To create build target matrix from selected target plaforms list'
inputs:
  buildEnvironment:
    required: true
    description: 'Build Environment'
    default: 'Development'
  buildTargetOne: 
    required: true
    description: 'Build target one'
    default: 'Android'
  buildTargetTwo: 
    required: true
    description: 'Build target two'
    default: 'None'
  buildTargetThree: 
    required: true
    description: 'Build target three'
    default: 'None'
  buildTargetFour: 
    required: true
    description: 'Build target four'
    default: 'None'
outputs:
  selectedTarget:
    description: Generated matrix
runs:
  using: 'node12'
  main: 'dist/index.js'
