name: 'Build Target Pre Processor'
description: 'To create build target matrix from selected target plaforms list'
inputs:
  buildEnvironment:
    required: false
    description: 'Build Environment'
    default: 'Development'
  slackChannel:
    required: false
    description: 'Output slack channel'
    default: 'Public'    
  buildTargetOne: 
    required: false
    description: 'Build target one'
    default: 'Android'
  buildTargetTwo: 
    required: false
    description: 'Build target two'
    default: 'None'
  buildTargetThree: 
    required: false
    description: 'Build target three'
    default: 'None'
  buildTargetFour: 
    required: false
    description: 'Build target four'
    default: 'None'
  slackData:
    required: true
    description: 'Slack channel selection data'
    default: '{"Public":"SLACK_WEBHOOK","Private":"SLACK_WEBHOOK_2"}'
  settingsFilePath:
    required: true
    description: 'Project settings file path'
    default: 'ProjectSettings/ProjectSettings.asset'

outputs:
  selectedTarget:
    description: Generated matrix
    
runs:
  using: 'node12'
  main: 'dist/index.js'
