name: 'Build Target Pre Processor'
description: 'To create build target matrix from selected target plaforms list'
inputs:
  buildEnvironment:
    required: false
    description: 'Build Environment'
    default: 'Development'
  slackChannel:
    required: false
    description: 'Output slack channel'
    default: 'Public'    
  buildTargetOne: 
    required: false
    description: 'Build target one'
    default: 'Android'
  buildTargetTwo: 
    required: false
    description: 'Build target two'
    default: 'None'
  buildTargetThree: 
    required: false
    description: 'Build target three'
    default: 'None'
  buildTargetFour: 
    required: false
    description: 'Build target four'
    default: 'None'
  buildTargetFive: 
    required: false
    description: 'Build target five'
    default: 'None'
  slackData:
    required: true
    description: 'Slack channel selection data'
    default: '{"Public":"SLACK_WEBHOOK","Private":"SLACK_WEBHOOK_2"}'
  buildNumberStepSize:
    required: true
    description: 'The fixed amount by which the build number is increased'
    default: '1'
  evironmentData:
    required: true
    description: 'Environment specific data'
    default: '{"Development":{"GCPKey":"SERVICE_ACCOUNT_KEY_DEV","GCPURL":"GCP_BUILD_URL_PREFIX_DEV","GCPURLPrefix":"indus-builds"},"Staging":{"GCPKey":"GCP_BUILD_URL_PREFIX_STAGING","GCPURL":"SERVICE_ACCOUNT_KEY_STAGING","GCPURLPrefix":"indus-builds-stage"},"Release":{"GCPKey":"GCP_BUILD_URL_PREFIX_STAGING","GCPURL":"SERVICE_ACCOUNT_KEY_STAGING","GCPURLPrefix":"indus-builds-stage"},"Production":{"GCPKey":"GCP_BUILD_URL_PREFIX_STAGING","GCPURL":"SERVICE_ACCOUNT_KEY_STAGING","GCPURLPrefix":"indus-builds-stage"}}'
  buildConfig:
    required: true
    description: 'Choosen build config'
    default: 'Default'
  buildConfigData:
    required: true
    description: 'List of build of configs'
    default: '{"Default":"Assets/Indus/Platform/Build/Configurations/Config.Build.Default.asset"}'
  buildNumberAPIKey:
    required: true
    description: 'Build number API key'
  overrideBuildNumber:
    required: true
    description: 'Enable overriding build number'
    default: false
  customBuildNumber:
    required: true
    description: 'Custom build number'
    default: false

outputs:
  selectedTarget:
    description: Generated matrix
  buildNumber:
    description: Build Number
    
runs:
  using: 'node12'
  main: 'dist/index.js'
