name: 'Build Target Pre Processor'
description: 'To create build target matrix from selected target plaforms list'
inputs:
  buildTarget: 
    required: true
    description: 'List of build targets'
    default: 'Android'
outputs:
  selectedTarget:
    description: Generated matrix
runs:
  using: 'node12'
  main: 'dist/index.js'
