name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      buildTarget:
        type: choice
        description: Who to greet
        options: 
        - Android
        - iOS
        - Windows 
        - Windows Server
        - Linux Server
        - Android, iOS
        - Android, iOS, Linux Server
        - Android, iOS, Windows Server

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      name: Run
    - name: Send greeting
      run: echo "${{ steps.Run.outputs.buildTarget }}" 