name: Mixed inputs

on:
  workflow_dispatch:

jobs:
  preBuilds:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.buildMatrix.outputs.selectedTarget }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      name: Build Matrix
      id: buildMatrix
      with: 
        buildEnvironment: "${{ github.event.inputs.buildEnvironment }}"
        buildTargetOne: "${{ github.event.inputs.buildTargetOne }}"
        buildTargetTwo: "${{ github.event.inputs.buildTargetTwo }}"
        buildTargetThree: "${{ github.event.inputs.buildTargetThree }}"
        buildTargetFour: "${{ github.event.inputs.buildTargetFour }}"
    - name: Send greeting
      run: echo "${{ steps.buildMatrix.outputs.selectedTarget }}" 
  build: #To create the builds
    needs: preBuilds
    name: Build for ${{ matrix.targetPlatform.customPlatformName }}
    runs-on: self-hosted-windows
    outputs:
      buildResult: ${{ steps.buildStep.outcome }}
    strategy:
      fail-fast: false
      matrix:
        targetPlatform: ${{ fromJson(needs.preBuilds.outputs.result) }}
    steps:
      - name: Check Out
        run: echo "${{ matrix.targetPlatform.platform }}" 