name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      buildEnvironment:
        type: choice
        description: Build Environment
        options:
        - Development
        - Production
      slackChannel:
        type: choice
        description: Slack Channel
        options:
        - Private
        - Public
      buildTargetOne:
        type: choice
        description: Build Target One
        options: 
        - None
        - Android
        - iOS
        - Windows 
        - Windows Server
        - Linux Server
      buildTargetTwo:
        type: choice
        description: Build Target Two
        options: 
        - None
        - Android
        - iOS
        - Windows 
        - Windows Server
        - Linux Server
      buildTargetThree:
        type: choice
        description: Build Target Three
        options: 
        - None
        - Android
        - iOS
        - Windows 
        - Windows Server
        - Linux Server
      buildTargetFour:
        type: choice
        description: Build Target Four
        options: 
        - None
        - Android
        - iOS
        - Windows 
        - Windows Server
        - Linux Server
      os:
        required: true
        default: '{"Windows":"self-hosted-windows-test","Mac":"self-hosted-mac-test","Common":"self-hosted-build-runner"}'
      slackData:
        required: true
        default: '{"Public":"SLACK_WEBHOOK","Private":"SLACK_WEBHOOK_2"}'

jobs:
  preBuilds:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.buildMatrix.outputs.selectedTarget }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      name: Build Matrix
      id: buildMatrix
      with: 
        buildEnvironment: "${{ github.event.inputs.buildEnvironment }}"
        buildTargetOne: "${{ github.event.inputs.buildTargetOne }}"
        buildTargetTwo: "${{ github.event.inputs.buildTargetTwo }}"
        buildTargetThree: "${{ github.event.inputs.buildTargetThree }}"
        buildTargetFour: "${{ github.event.inputs.buildTargetFour }}"
        os: "${{ github.event.inputs.os }}"
        slackChannel: "${{ github.event.inputs.slackChannel }}"
        slackData: "${{ github.event.inputs.slackData }}"
    - name: Send greeting
      run: echo "${{ steps.buildMatrix.outputs.selectedTarget }}" 
  build: #To create the builds
    needs: preBuilds
    name: Build for ${{ matrix.targetPlatform.customPlatformName }}
    runs-on: ${{ matrix.targetPlatform.os }}
    outputs:
      buildResult: ${{ steps.buildStep.outcome }}
    strategy:
      fail-fast: false
      matrix:
        targetPlatform: ${{ fromJson(needs.preBuilds.outputs.result) }}
    steps:
      - name: Check Out
        run: echo "${{ matrix.targetPlatform.platform }}" 