name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      buildTarget:
        type: choice
        description: Who to greet
        options: 
        - Android
        - iOS
        - Windows 
        - Windows Server
        - Linux Server
        - Android, iOS
        - Android, iOS, Linux Server
        - Android, iOS, Windows Server
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include  emojis
      environment:
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.buildTarget }}"